# Generated by Django 2.2.6 on 2019-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='students_ids',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userform',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
