# Generated by Django 2.2.6 on 2019-11-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputform', '0002_auto_20191101_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
