# Generated by Django 2.2.6 on 2019-11-01 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputform', '0003_auto_20191101_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
